### ISSUE TITLE
Dynamic Matrix Syntax Error

### ISSUE THREAD

**Issue by jakemaguy** [camunda-community-hub/camunda-jenkins-shared-library#1]
Jenkins v2.333

## Steps to Reproduce issue

1. Add camunda shared jenkins library to jenkins instance by going to:
Manage Jenkins -> Configure System -> Global Pipeline Libraries
2. Add a Library with the following configuration:
```
name: camunda-community
Default Version: main
Retrieval Method: Modern SCM
Source Code Management: git
Project Repository: https://github.com/camunda-community-hub/camunda-jenkins-shared-library.git
Credentials:
```
3.  Create a pipeline job and use the following pipeline script:
```
@Library('camunda-community') _

pipeline {
    agent any
    stages{
        stage('single_matrix') {
            steps {
                dynamicMatrix([
                    failFast: false,
                    axes: [
                        PLATFORM: ['linux', 'mac', 'windows'],
                        BROWSER: ['chrome', 'firefox', 'safari']
                    ],
                    actions: {
                        stage("${PLATFORM}_${BROWSER}") {
                            sh 'echo ${PLATFORM} - ${BROWSER}'
                            sh 'echo ${MATRIX_STAGE_NAME}'
                        }
                    }
                ])
            }
        }
    }
}
```
## Error Message

```
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (single_matrix)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
org.jenkinsci.plugins.workflow.cps.CpsCompilationErrorsException: startup failed:
/var/jenkins_home/jobs/SCRATCH_MULTIBRANCH/branches/azt-mimic.2mc81s/builds/59/libs/camunda-community/vars/dynamicMatrix.groovy: 109: expecting '}', found '[' @ line 109, column 10.
       echo "[${stepName}] Invalid parameter '${parameter}'. Available parameter are: ${availableParameters}"
            ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:349)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:225)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:191)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:233)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:189)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:966)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:786)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:743)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:812)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader.loadClass(CpsGroovyShell.java:170)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:702)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:812)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:800)
	at org.jenkinsci.plugins.workflow.cps.global.UserDefinedGlobalVariable.getValue(UserDefinedGlobalVariable.java:57)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at sun.reflect.GeneratedMethodAccessor532.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:8)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.delegateAndExecute(ModelInterpreter.groovy:137)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executeSingleStage(ModelInterpreter.groovy:666)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:395)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:393)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executeSingleStage(ModelInterpreter.groovy:665)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:288)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.toolsBlock(ModelInterpreter.groovy:544)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.toolsBlock(ModelInterpreter.groovy:543)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:276)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:443)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:442)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:275)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:481)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:480)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:274)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:586)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:585)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:272)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:356)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:355)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:261)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:618)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:617)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:259)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:443)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:442)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:254)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor446.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor449.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:402)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:314)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:278)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by ArthurMargerit** [comment]
i get the same

**Comment by ArthurMargerit** [comment]
i Patch it: https://github.com/ArthurMargerit/camunda-jenkins-shared-library

**Comment by aabouzaid** [comment]
@jakemaguy Thanks for reporting this issue, I've fixed it. Please give it a try now.

**Comment by jakemaguy** [comment]
@aabouzaid 
Just verified that it is working now:
```
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (single_matrix)
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=linux, BROWSER=chrome, MATRIX_STAGE_VARS=PLATFORM=linux, BROWSER=chrome, MATRIX_STAGE_NAME=linux_chrome]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=mac, BROWSER=chrome, MATRIX_STAGE_VARS=PLATFORM=mac, BROWSER=chrome, MATRIX_STAGE_NAME=mac_chrome]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=windows, BROWSER=chrome, MATRIX_STAGE_VARS=PLATFORM=windows, BROWSER=chrome, MATRIX_STAGE_NAME=windows_chrome]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=linux, BROWSER=firefox, MATRIX_STAGE_VARS=PLATFORM=linux, BROWSER=firefox, MATRIX_STAGE_NAME=linux_firefox]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=mac, BROWSER=firefox, MATRIX_STAGE_VARS=PLATFORM=mac, BROWSER=firefox, MATRIX_STAGE_NAME=mac_firefox]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=windows, BROWSER=firefox, MATRIX_STAGE_VARS=PLATFORM=windows, BROWSER=firefox, MATRIX_STAGE_NAME=windows_firefox]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=linux, BROWSER=safari, MATRIX_STAGE_VARS=PLATFORM=linux, BROWSER=safari, MATRIX_STAGE_NAME=linux_safari]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=mac, BROWSER=safari, MATRIX_STAGE_VARS=PLATFORM=mac, BROWSER=safari, MATRIX_STAGE_NAME=mac_safari]
[Pipeline] echo
[dynamicMatrix] Matrix group vars are:
 [PLATFORM=windows, BROWSER=safari, MATRIX_STAGE_VARS=PLATFORM=windows, BROWSER=safari, MATRIX_STAGE_NAME=windows_safari]
[Pipeline] parallel
[Pipeline] { (Branch: PLATFORM=linux, BROWSER=chrome)
[Pipeline] { (Branch: PLATFORM=mac, BROWSER=chrome)
[Pipeline] { (Branch: PLATFORM=windows, BROWSER=chrome)
[Pipeline] { (Branch: PLATFORM=linux, BROWSER=firefox)
[Pipeline] { (Branch: PLATFORM=mac, BROWSER=firefox)
[Pipeline] { (Branch: PLATFORM=windows, BROWSER=firefox)
[Pipeline] { (Branch: PLATFORM=linux, BROWSER=safari)
[Pipeline] { (Branch: PLATFORM=mac, BROWSER=safari)
[Pipeline] { (Branch: PLATFORM=windows, BROWSER=safari)
[Pipeline] stage
[Pipeline] { (PLATFORM=linux, BROWSER=chrome)
[Pipeline] stage
[Pipeline] { (PLATFORM=mac, BROWSER=chrome)
[Pipeline] stage
[Pipeline] { (PLATFORM=windows, BROWSER=chrome)
[Pipeline] stage
[Pipeline] { (PLATFORM=linux, BROWSER=firefox)
[Pipeline] stage
[Pipeline] { (PLATFORM=mac, BROWSER=firefox)
[Pipeline] stage
[Pipeline] { (PLATFORM=windows, BROWSER=firefox)
[Pipeline] stage
[Pipeline] { (PLATFORM=linux, BROWSER=safari)
[Pipeline] stage
[Pipeline] { (PLATFORM=mac, BROWSER=safari)
[Pipeline] stage
[Pipeline] { (PLATFORM=windows, BROWSER=safari)
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (linux_chrome)
[Pipeline] stage
[Pipeline] { (mac_chrome)
[Pipeline] stage
[Pipeline] { (windows_chrome)
[Pipeline] stage
[Pipeline] { (linux_firefox)
[Pipeline] stage
[Pipeline] { (mac_firefox)
[Pipeline] stage
[Pipeline] { (windows_firefox)
[Pipeline] stage
[Pipeline] { (linux_safari)
[Pipeline] stage
[Pipeline] { (mac_safari)
[Pipeline] stage
[Pipeline] { (windows_safari)
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
+ echo linux - chrome
linux - chrome
+ echo mac - chrome
mac - chrome
+ echo windows - chrome
windows - chrome
+ echo linux - firefox
linux - firefox
[Pipeline] sh
+ echo mac - firefox
mac - firefox
[Pipeline] sh
+ echo windows - firefox
windows - firefox
+ echo linux - safari
linux - safari
[Pipeline] sh
+ echo mac - safari
mac - safari
[Pipeline] sh
+ echo windows - safari
windows - safari
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
[Pipeline] sh
+ echo linux_chrome
linux_chrome
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
+ echo mac_chrome
mac_chrome
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
+ echo windows_chrome
windows_chrome
+ echo linux_firefox
linux_firefox
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
+ echo mac_firefox
mac_firefox
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
+ echo windows_firefox
windows_firefox
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
+ echo linux_safari
linux_safari
+ echo mac_safari
mac_safari
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
+ echo windows_safari
windows_safari
[Pipeline] // withEnv
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
Thank you for looking into this
